### ISSUE TITLE
The star link is outdated and no longer used.

### ISSUE THREAD

**Issue by amitfenn** [genome/docker-star#5]
Hey Sridar,

Thanks for putting this dockerfile on the net for others to learn from. Just to let you know however, I tried to manually follow that link and it doesn't seem to be workign anymore.

This is the new link now : https://github.com/alexdobin/STAR/archive/2.7.3a.tar.gz

I guess it's just a tiny matter of changing the ENV star_version 2.7.0f to 2.7.3a.tar.gz

**Comment by amitfenn** [comment]
This is the new link now : https://github.com/alexdobin/STAR/archive/2.7.3a.tar.gz

**Comment by amitfenn** [comment]
Also, RUN command on line 40, it's better if we use the variable ${star_version} there.

**Comment by sridhar0605** [comment]
Thanks , i guess OP has changed/reorganized the directory structure. We use this image for most of the pipelines and would not affect them for now, except in case i build the same image again. 

Thanks for inputs. 
Sridhar
